---
- name: update zookeeper conf
  template:
    src: zookeeper.properties
    dest: "/app/kafka/config/zookeeper.properties"
    owner: "vagrant"
    group: "vagrant"

- name: restart zookeeper
  service: name=zookeeper enabled=yes state=restarted

- name: restart kafka
  service: name=kafka enabled=yes state=restarted