---
- name: check kafka brokers
  command: chdir=/app/kafka/bin ./zookeeper-shell.sh {{ groups['kafka_servers'][0] }}:2181 ls /brokers/ids
  register: output
  until: "'[1, 2, 3, 4, 5, 6]' in output.stdout_lines"
  retries: 3
  delay: 10

- debug:
    var: output

- name: H01 - assert kafka cluster is ok
  assert:
    that:
        - "'[1, 2, 3, 4, 5, 6]' in output.stdout_lines"

- name: delete kafka test topic
  command: chdir=/app/kafka/bin ./kafka-topics.sh --delete --zookeeper {{ groups['kafka_servers'][0] }}:2181,{{ groups['kafka_servers'][1] }}:2181,{{ groups['kafka_servers'][2] }}:2181,{{ groups['kafka_servers'][3] }}:2181,{{ groups['kafka_servers'][4] }}:2181,{{ groups['kafka_servers'][5] }}:2181 --topic test
  register: output
  failed_when: "' does not exist ' not in output.stderr and output.rc != 0"

- debug:
    var: output

- name: create kafka test topic replication factor 5, partition 1
  command: chdir=/app/kafka/bin ./kafka-topics.sh --create --zookeeper {{ groups['kafka_servers'][0] }}:2181,{{ groups['kafka_servers'][1] }}:2181,{{ groups['kafka_servers'][2] }}:2181,{{ groups['kafka_servers'][3] }}:2181,{{ groups['kafka_servers'][4] }}:2181,{{ groups['kafka_servers'][5] }}:2181 --replication-factor 5 --partitions 1 --topic test
  register: output

- debug:
    var: output

- name: publish a test message to the kafka test topic
  shell: chdir=/app/kafka/bin echo "testmsg" | ./kafka-console-producer.sh --broker-list {{ groups['kafka_servers'][0] }}:9092,{{ groups['kafka_servers'][1] }}:9092,{{ groups['kafka_servers'][2] }}:9092,{{ groups['kafka_servers'][3] }}:9092,{{ groups['kafka_servers'][4] }}:9092,{{ groups['kafka_servers'][5] }}:9092 --request-required-acks all --topic test
  register: output

- debug:
    var: output

- name: consume test message from kafka test topic on group 2 servers
  command: chdir=/app/kafka/bin ./kafka-console-consumer.sh --bootstrap-server {{ groups['kafka_servers'][0] }}:9092,{{ groups['kafka_servers'][1] }}:9092,{{ groups['kafka_servers'][2] }}:9092,{{ groups['kafka_servers'][3] }}:9092,{{ groups['kafka_servers'][4] }}:9092,{{ groups['kafka_servers'][5] }}:9092 --topic test --from-beginning -timeout-ms 5000
  register: output
  delegate_to: "{{ groups['kafka_servers_dc2'][0] }}"

- debug:
    var: output

#./kafka-topics.sh --describe --topic test --zookeeper 192.168.33.60:2181

- name: H05 - assert kafka data replication is ok from a server in dc2 group
  assert:
    that:
        - "'testmsg' in output.stdout_lines"