---
- hosts: kafka_servers_dc1
  gather_facts: yes
  become: yes
  become_method: sudo
  tasks:
    - include_role:
        name: kafka
        tasks_from: dcfailover.yml
      vars:
        ansible_zookeeper_failover_to_dc1: true