---
- hosts: kafka_servers
  gather_facts: yes
  become: yes
  become_method: sudo
  # pre_tasks:
  #   - include_role:
  #       name: kafka
  #       tasks_from: dcfailoverandrestore.yml
  tasks:
    - include_role:
        name: kafka
        tasks_from: tests.yml
      run_once: true